// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/mapserver2007/mcp-server-golang-poc/app/infrastructure/mcp"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func NewMcpServer(logger *logrus.Logger) *mcp.Server {
	server := mcp.NewServer(logger)
	return server
}
